<?php

if (function_exists('acf_add_local_field_group')) :

    acf_add_local_field_group(array(
        'key' => 'group_5f899567dd342',
        'title' => 'Расписание - запись',
        'fields' => array(
            array(
                'key' => 'field_5f8d184d4ff7a',
                'label' => 'Вывести заголовок страницы или выбор тренировок',
                'name' => 'show_heading_or_select_meta',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 1,
                'ui' => 1,
                'ui_on_text' => 'Список',
                'ui_off_text' => 'Заголовок',
            ),
            array(
                'key' => 'field_5f8d18c74ff7b',
                'label' => 'Выбор тренировки',
                'name' => 'select_trening',
                'type' => 'taxonomy',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5f8d184d4ff7a',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'taxonomy' => 'workoutspost',
                'field_type' => 'radio',
                'allow_null' => 0,
                'add_term' => 1,
                'save_terms' => 1,
                'load_terms' => 1,
                'return_format' => 'object',
                'multiple' => 0,
            ),
            array(
                'key' => 'field_60a3da5e5e90c',
                'label' => 'День недели проведения тренировки',
                'name' => 'week_time_traning',
                'type' => 'checkbox',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'Понедельник' => 'Понедельник',
                    'Вторник' => 'Вторник',
                    'Среда' => 'Среда',
                    'Четверг' => 'Четверг',
                    'Пятница' => 'Пятница',
                    'Суббота' => 'Суббота',
                    'Воскресенье' => 'Воскресенье',
                ),
                'allow_custom' => 0,
                'default_value' => array(),
                'layout' => 'horizontal',
                'toggle' => 0,
                'return_format' => 'value',
                'save_custom' => 0,
            ),
            array(
                'key' => 'field_5f8a228bc5128',
                'label' => 'Цвет',
                'name' => 'color',
                'type' => 'radio',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    '#e71c8a' => 'Розовый',
                    '#e55454' => 'Красный',
                    '#ff9d2e' => 'Оранжевый',
                    '#5ca84c' => 'Зеленый',
                    '#9a1fbe' => 'Фиолетовый',
                ),
                'allow_null' => 0,
                'other_choice' => 1,
                'save_other_choice' => 1,
                'default_value' => '',
                'layout' => 'vertical',
                'return_format' => 'value',
            ),
            array(
                'key' => 'field_5f899579d8d29',
                'label' => 'Время начала',
                'name' => 'time_start',
                'type' => 'time_picker',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'display_format' => 'H:i',
                'return_format' => 'H:i',
            ),
            array(
                'key' => 'field_5f8995c0d8d2a',
                'label' => 'Время завершения',
                'name' => 'time_end',
                'type' => 'time_picker',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'display_format' => 'H:i',
                'return_format' => 'H:i',
            ),
            array(
                'key' => 'field_5f8995d6d8d2b',
                'label' => 'Стоимость',
                'name' => 'price',
                'type' => 'number',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'min' => '',
                'max' => '',
                'step' => '',
            ),
            array(
                'key' => 'field_5f8ac578d5b1b',
                'label' => 'Как выделить?',
                'name' => 'show_how',
                'type' => 'radio',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'border' => 'Только обводку',
                    'color' => 'Залить цветом',
                    'gray' => 'Выделить серым цветом',
                ),
                'allow_null' => 0,
                'other_choice' => 0,
                'default_value' => '',
                'layout' => 'horizontal',
                'return_format' => 'value',
                'save_other_choice' => 0,
            ),
            array(
                'key' => 'field_5f8d64d663eb8',
                'label' => 'Ссылка по нажатию',
                'name' => 'link_on_click',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '#modal-form',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_60c249a709745',
                'label' => 'Указать даты, когда не нужно выводить тренировку',
                'name' => 'date_minus',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'table',
                'button_label' => 'Добавить дату отсутствия тренировки',
                'sub_fields' => array(
                    array(
                        'key' => 'field_60c249d109746',
                        'label' => 'Дата',
                        'name' => 'date_minus_in',
                        'type' => 'date_picker',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'display_format' => 'd.m.Y',
                        'return_format' => 'd.m.Y',
                        'first_day' => 1,
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'timetables',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'acf_after_title',
        'style' => 'seamless',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => array(
            0 => 'the_content',
            1 => 'page_attributes',
            2 => 'tags',
        ),
        'active' => true,
        'description' => '',
    ));

endif;
